CREATE (:`Country` {import_name: '[Nước Cộng hòa xã hội chủ nghĩa Việt Nam'  })
CREATE (:`Country` {import_name: 'Nhà nước'  })
CREATE (:`Country` {import_name: 'Cộng hòa xã hội chủ nghĩa Việt Nam'  })
CREATE (:`Country` {import_name: 'nền văn hóa Việt Nam'  })
CREATE (:`Country` {import_name: 'văn học'  })
CREATE (:`Country` {import_name: 'nghệ thuật'  })
CREATE (:`Country` {import_name: 'phương tiện thông tin đại chúng'  })
CREATE (:`Country` {import_name: 'gia đình Việt Nam'  })
CREATE (:`Country` {import_name: 'con người Việt Nam'  })
CREATE (:`Country` {import_name: 'giáo dục'  })
CREATE (:`Country` {import_name: 'dân trí'  })
CREATE (:`Country` {import_name: 'nguồn nhân lực'  })
CREATE (:`Country` {import_name: 'nhân tài'  })
CREATE (:`Country` {import_name: 'khoa học'  })
CREATE (:`Country` {import_name: 'công nghệ'  })
CREATE (:`Country` {import_name: 'môi trường'  })
CREATE (:`Country` {import_name: 'tài nguyên thiên nhiên'  })
CREATE (:`Country` {import_name: 'năng lượng mới'  })
CREATE (:`Country` {import_name: 'năng lượng tái tạo'  })
CREATE (:`Country` {import_name: 'Chính phủ'  })
CREATE (:`Country` {import_name: 'Các đơn vị hành chính của nước Cộng hòa xã hội chủ nghĩa Việt Nam'  })
CREATE (:`Country` {import_name: 'Việt Nam'  })
CREATE (:`People` {import_name: 'Nhân dân Việt Nam'  })
CREATE (:`People` {import_name: 'Công dân'  })
CREATE (:`People` {import_name: 'Nam'  })
CREATE (:`People` {import_name: 'Nữ'  })
CREATE (:`People` {import_name: 'Phụ nữ'  })
CREATE (:`People` {import_name: 'Gia đình'  })
CREATE (:`People` {import_name: 'Cá nhân'  })
CREATE (:`People` {import_name: 'Luật sư'  })
CREATE (:`People` {import_name: 'người mẹ'  })
CREATE (:`People` {import_name: 'trẻ em'  })
CREATE (:`People` {import_name: 'người có công với nước'  })
CREATE (:`People` {import_name: 'người cao tuổi'  })
CREATE (:`People` {import_name: 'người khuyết tật'  })
CREATE (:`People` {import_name: 'người nghèo'  })
CREATE (:`People` {import_name: 'người có hoàn cảnh khó khăn khác'  })
CREATE (:`People` {import_name: 'đại biểu Quốc hội'  })
CREATE (:`People` {import_name: 'Chủ tịch nước'  })
CREATE (:`People` {import_name: 'Chủ tịch Hội đồng dân tộc'  })
CREATE (:`People` {import_name: 'Chủ nhiệm Ủy ban của Quốc hội'  })
CREATE (:`People` {import_name: 'Chủ tịch Hội đồng bầu cử quốc gia'  })
CREATE (:`People` {import_name: 'Tổng Kiểm toán nhà nước'  })
CREATE (:`People` {import_name: 'đồng bào ở miền núi'  })
CREATE (:`People` {import_name: 'Chủ tịch Quốc hội'  })
CREATE (:`People` {import_name: 'Thủ tướng Chính phủ'  })
CREATE (:`People` {import_name: 'Bộ trưởng'  })
CREATE (:`People` {import_name: 'Chánh án Tòa án nhân dân tối cao'  })
CREATE (:`People` {import_name: 'Viện trưởng Viện kiểm sát nhân dân tối cao'  })
CREATE (:`People` {import_name: 'Tổng Kiểm toán Nhà nước'  })
CREATE (:`People` {import_name: 'Phó Chủ tịch nước'  })
CREATE (:`People` {import_name: 'Phó Thủ tướng Chính phủ'  })
CREATE (:`People` {import_name: 'Thủ trưởng cơ quan ngang bộ'  })
CREATE (:`People` {import_name: 'Viện trưởng các Viện kiểm sát khác'  })
CREATE (:`People` {import_name: 'Viện trưởng'  })
CREATE (:`People` {import_name: 'Kiểm sát viên'  })
CREATE (:`Political Party` {import_name: 'Đảng Cộng sản Việt Nam'  })
CREATE (:`Political Party` {import_name: 'Quốc hội'  })
CREATE (:`Political Party` {import_name: 'Hội đồng nhân dân'  })
CREATE (:`Political Party` {import_name: 'Cơ quan nhà nước'  })
CREATE (:`Political Party` {import_name: 'Cơ quan'  })
CREATE (:`Political Party` {import_name: 'Tổ chức'  })
CREATE (:`Political Party` {import_name: 'Tòa án'  })
CREATE (:`Political Party` {import_name: 'Doanh nghiệp'  })
CREATE (:`Political Party` {import_name: 'Tổ chức kinh tế'  })
CREATE (:`Political Party` {import_name: 'Nhà nước'  })
CREATE (:`Political Party` {import_name: 'xã hội'  })
CREATE (:`Political Party` {import_name: 'gia đình'  })
CREATE (:`Political Party` {import_name: 'Quân đội nhân dân'  })
CREATE (:`Political Party` {import_name: 'Công an nhân dân'  })
CREATE (:`Political Party` {import_name: 'Political Party'  })
CREATE (:`Political Party` {import_name: 'Ủy ban thường vụ Quốc hội'  })
CREATE (:`Political Party` {import_name: 'Hội đồng dân tộc'  })
CREATE (:`Political Party` {import_name: 'Ủy ban của Quốc hội'  })
CREATE (:`Political Party` {import_name: 'Chính phủ'  })
CREATE (:`Political Party` {import_name: 'Tòa án nhân dân tối cao'  })
CREATE (:`Political Party` {import_name: 'Viện kiểm sát nhân dân tối cao'  })
CREATE (:`Political Party` {import_name: 'Kiểm toán nhà nước'  })
CREATE (:`Political Party` {import_name: 'Ủy ban trung ương Mặt trận Tổ quốc Việt Nam'  })
CREATE (:`Political Party` {import_name: 'cơ quan trung ương của tổ chức thành viên của Mặt trận'  })
CREATE (:`Political Party` {import_name: 'Mặt trận Tổ quốc Việt Nam'  })
CREATE (:`Political Party` {import_name: 'cơ quan trung ương của tổ chức chính trị'  })
CREATE (:`Type` {import_name: 'Political Party'  })
CREATE (:`Type` {import_name: 'đồng bào ở miền núi'  })
CREATE (:`Type` {import_name: 'People'  })
CREATE (:`Type` {import_name: 'Country'  })
CREATE (:`Type` {import_name: 'Quốc hội'  })
CREATE (:`Type` {import_name: 'Ủy ban thường vụ Quốc hội'  })
CREATE (:`Type` {import_name: 'Chủ tịch Quốc hội'  })
CREATE (:`Type` {import_name: 'Phó Chủ tịch Quốc hội'  })
CREATE (:`Type` {import_name: 'Ủy viên'  })
CREATE (:`Type` {import_name: 'Chính phủ'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Viện kiểm sát nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Kiểm toán Nhà nước'  })
CREATE (:`Type` {import_name: 'Hội đồng dân tộc'  })
CREATE (:`Type` {import_name: 'Hội đồng nhân dân'  })
CREATE (:`Type` {import_name: 'Chủ tịch Hội đồng dân tộc'  })
CREATE (:`Type` {import_name: 'Phó Chủ tịch Hội đồng dân tộc'  })
CREATE (:`Type` {import_name: 'Ủy viên Hội đồng dân tộc'  })
CREATE (:`Type` {import_name: 'Ủy ban của Quốc hội'  })
CREATE (:`Type` {import_name: 'Chủ nhiệm Ủy ban'  })
CREATE (:`Type` {import_name: 'Phó Chủ nhiệm Ủy ban'  })
CREATE (:`Type` {import_name: 'Ủy viên Ủy ban'  })
CREATE (:`Type` {import_name: 'Chính phủ'  })
CREATE (:`Type` {import_name: 'Chánh án Tòa án nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Viện trưởng Viện kiểm sát nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Tổng Kiểm toán nhà nước'  })
CREATE (:`Type` {import_name: 'đại sứ đặc mệnh toàn quyền của Cộng hòa xã hội chủ nghĩa Việt Nam'  })
CREATE (:`Type` {import_name: 'Thủ tướng Chính phủ'  })
CREATE (:`Type` {import_name: 'Chánh án Tòa án nhân dân'  })
CREATE (:`Type` {import_name: 'Viện trưởng Viện kiểm sát nhân dân'  })
CREATE (:`Type` {import_name: 'Thẩm phán Tòa án nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Phó Chánh án Tòa án nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Thẩm phán các Tòa án khác'  })
CREATE (:`Type` {import_name: 'Phó Viện trưởng'  })
CREATE (:`Type` {import_name: 'Kiểm sát viên Viện kiểm sát nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Hội đồng quốc phòng và an ninh'  })
CREATE (:`Type` {import_name: 'Tổng tham mưu trưởng'  })
CREATE (:`Type` {import_name: 'Chủ nhiệm Tổng cục chính trị Quân đội nhân dân Việt Nam'  })
CREATE (:`Type` {import_name: 'Thủ tướng Chính phủ'  })
CREATE (:`Type` {import_name: 'Phó Thủ tướng Chính phủ'  })
CREATE (:`Type` {import_name: 'Bộ trưởng'  })
CREATE (:`Type` {import_name: 'Thành viên'  })
CREATE (:`Type` {import_name: 'Chủ tịch Ủy ban nhân dân tỉnh'  })
CREATE (:`Type` {import_name: 'Phó Chủ tịch Ủy ban nhân dân tỉnh'  })
CREATE (:`Type` {import_name: 'Hội đồng nhân dân tỉnh'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân'  })
CREATE (:`Type` {import_name: 'Viện kiểm sát nhân dân'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân'  })
CREATE (:`Type` {import_name: 'Tòa án khác'  })
CREATE (:`Type` {import_name: 'Hội thẩm'  })
CREATE (:`Type` {import_name: 'Thẩm phán'  })
CREATE (:`Type` {import_name: 'Việc xét xử sơ thẩm'  })
CREATE (:`Type` {import_name: 'Việc xét xử theo thủ tục rút gọn'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân có Hội thẩm tham gia'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân xét xử công khai'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân xét xử kín'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân xét xử tập thể'  })
CREATE (:`Type` {import_name: 'Nguyên tắc tranh tụng trong xét xử'  })
CREATE (:`Type` {import_name: 'Chế độ xét xử sơ thẩm'  })
CREATE (:`Type` {import_name: 'Chế độ xét xử phúc thẩm'  })
CREATE (:`Type` {import_name: 'Quyền bào chữa của bị can'  })
CREATE (:`Type` {import_name: 'Quyền bảo vệ lợi ích hợp pháp của đương sự'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân tối cao là cơ quan xét xử cao nhất'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân tối cao giám đốc việc xét xử của các Tòa án khác'  })
CREATE (:`Type` {import_name: 'Tòa án nhân dân tối cao thực hiện việc tổng kết thực tiễn xét xử'  })
CREATE (:`Type` {import_name: 'Chánh án Tòa án nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Chánh án Tòa án khác'  })
CREATE (:`Type` {import_name: 'Thẩm phán'  })
CREATE (:`Type` {import_name: 'Hội thẩm'  })
CREATE (:`Type` {import_name: 'Viện kiểm sát nhân dân'  })
CREATE (:`Type` {import_name: 'Viện kiểm sát nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Viện kiểm sát khác'  })
CREATE (:`Type` {import_name: 'Viện trưởng Viện kiểm sát nhân dân tối cao'  })
CREATE (:`Type` {import_name: 'Tỉnh'  })
CREATE (:`Type` {import_name: 'Thành phố trực thuộc trung ương'  })
CREATE (:`Type` {import_name: 'Huyện'  })
CREATE (:`Type` {import_name: 'Thị xã'  })
CREATE (:`Type` {import_name: 'Thành phố thuộc tỉnh'  })
CREATE (:`Type` {import_name: 'Quận'  })
CREATE (:`Type` {import_name: 'Xã'  })
CREATE (:`Type` {import_name: 'Thị trấn'  })
CREATE (:`Type` {import_name: 'Phường'  })
CREATE (:`Type` {import_name: 'Đơn vị hành chính - kinh tế đặc biệt'  })
CREATE (:`Type` {import_name: 'Hội đồng nhân dân'  })
CREATE (:`Type` {import_name: 'Ủy ban nhân dân'  })
CREATE (:`Type` {import_name: 'Đại biểu Hội đồng nhân dân'  })
CREATE (:`Type` {import_name: 'Chủ tịch Ủy ban nhân dân'  })
CREATE (:`Type` {import_name: 'Mặt trận Tổ quốc Việt Nam'  })
CREATE (:`Type` {import_name: 'Hội đồng bầu cử quốc gia'  })
CREATE (:`Type` {import_name: 'Kiểm toán nhà nước'  })
CREATE (:`Type` {import_name: 'Tổng Kiểm toán nhà nước'  })
CREATE (:`Type` {import_name: 'Hiến pháp'  })
CREATE (:`Type` {import_name: 'Ủy ban dự thảo Hiến pháp'  })
CREATE (:`đồng bào ở miền núi` {import_name: 'n chăm sóc sức khoẻ cho đồng bào dân tộc thiểu số'  });